export enum Events {
    SNAKE_MOVED,
    SNAKE_ATE,
    SNAKE_DIRECTION_CHANGED,
    GAME_BEGAN,
    GAME_OVER,
    MILLISECONDS_PER_TILE_CHANGED,
    FOOD_CREATED,
    SNAKE_HOLE_CREATION,
    SNAKE_ENTERED_HOLE,
    SNAKE_DIED,
}
